In [6]:
#Lab Assignment – 2 (Complete Solutions)
'''1. Create a data fil by using Python random module with different random generator parameters.
The data file must have 20000 × 10000 (rows × columns).
'''
import random
import csv

rows = 20000
cols = 10000

with open("large_matrix.csv", "w", newline="") as file:
    writer = csv.writer(file)
    for i in range(rows):
        row = [random.randint(1, 100) for _ in range(cols)]
        writer.writerow(row)

print("File created successfully.")

File created successfully.


In [7]:
'''Question 2 Write a program in Python to assign subsequent rows to matrix first row elements.'''
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Original Matrix:")
print(matrix)

first_row = matrix[0]

for i in range(1, len(matrix)):
    matrix[i] = first_row

print("Modified Matrix:")
print(matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Modified Matrix:
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [8]:
'''Question 3Write a program in Python to group similar elements into matrix.'''
import numpy as np

matrix = np.array([
    [1, 2, 2],
    [3, 1, 3],
    [2, 3, 1]
])

print("Matrix:")
print(matrix)

unique_elements = np.unique(matrix)

grouped = {}

for value in unique_elements:
    grouped[value] = np.where(matrix == value)

print("Grouped Elements:")
print(grouped)

Matrix:
[[1 2 2]
 [3 1 3]
 [2 3 1]]
Grouped Elements:
{np.int64(1): (array([0, 1, 2]), array([0, 1, 2])), np.int64(2): (array([0, 0, 2]), array([1, 2, 0])), np.int64(3): (array([1, 1, 2]), array([0, 2, 1]))}


In [9]:
'''Question 4 Write a program in Python to add and subtract matrices.'''
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("Matrix A:")
print(A)

print("Matrix B:")
print(B)

addition = A + B
subtraction = A - B

print("Addition:")
print(addition)

print("Subtraction:")
print(subtraction)

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Addition:
[[ 6  8]
 [10 12]]
Subtraction:
[[-4 -4]
 [-4 -4]]


In [10]:
''' Question 5 Write a program in Python to create an n × n square matrix, where all the sub-matrix has the sum of opposite corner elements as even.'''
import numpy as np

n = 4

matrix = np.random.randint(1, 50, size=(n,n)) * 2

print("Matrix:")
print(matrix)

Matrix:
[[ 4 62 68  8]
 [90 38  4 40]
 [60 52 46 38]
 [52 28 20 34]]


In [11]:
'''Question 6 Write a program in Python to perform row-wise element addition in tuple matrix.'''
matrix = (
    (1,2,3),
    (4,5,6),
    (7,8,9)
)

print("Tuple Matrix:")
print(matrix)

result = []

for row in matrix:
    result.append(sum(row))

print("Row-wise Addition:")
print(result)

Tuple Matrix:
((1, 2, 3), (4, 5, 6), (7, 8, 9))
Row-wise Addition:
[6, 15, 24]
